/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cybele_sodium_SodiumJNI */

#ifndef _Included_org_cybele_sodium_SodiumJNI
#define _Included_org_cybele_sodium_SodiumJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cybele_sodium_SodiumJNI
 * Method:    sodium_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cybele_sodium_SodiumJNI_sodium_1init
  (JNIEnv *, jclass);

/*
 * Class:     org_cybele_sodium_SodiumJNI
 * Method:    randombytes_random
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cybele_sodium_SodiumJNI_randombytes_1random
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
